version: "3"

services:
  transithub:
    image: princip/transithub-client:1.0.2
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./env.json:/src/.env.json
    logging:
      options:
        max-size: "50m"
    command:
      "npm run start"

  nginx:
    image: nginx:1.15
    container_name: nginx
    logging:
      options:
        max-size: "50m"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - transithub
