export const MUTATIONS_KEYS = Object.freeze({
  APPEND_TO_LIST: 'APPEND_TO_LIST',
  SET_COUNT: 'SET_COUNT',
  SET_LOADING: 'SET_LOADING',
  SET_OFFSET: 'SET_OFFSET',
  SET_ITEM: 'SET_ITEM'
})

export const ACTIONS_KEYS = Object.freeze({
  FETCH_LIST: 'FETCH_LIST',
  FETCH_ITEM: 'FETCH_ITEM'
})
