export const MUTATIONS_KEYS = Object.freeze({
  SET_LIST: 'SET_LIST',
  SET_LOADING: 'SET_LOADING',

  SET_SUBORDINATE_LIST: 'SET_SUBORDINATE_LIST',
  CHANGE_SUBORDINATE_LIST_ITEM: 'CHANGE_SUBORDINATE_LIST_ITEM',
  SET_SUBORDINATE_LOADING: 'SET_SUBORDINATE_LOADING',
  SET_SUBORDINATE_VISIBILE: 'SET_SUBORDINATE_VISIBILE',
  SET_SUBORDINATE_WAREHOUSE: 'SET_SUBORDINATE_WAREHOUSE',

  SET_BIND_LOADING: 'SET_BIND_LOADING',
})

export const GETTERS_KEYS = Object.freeze({
  COMBINED: 'COMBINED',
})

export const ACTIONS_KEYS = Object.freeze({
  FETCH_LIST: 'FETCH_LIST',
  FETCH_SUBORDINATE_LIST: 'FETCH_SUBORDINATE_LIST',

  BIND_GOODS_TO_WAREHOUSE: 'BIND_GOODS_TO_WAREHOUSE',
  UNBIND_GOODS_TO_WAREHOUSE: 'UNBIND_GOODS_TO_WAREHOUSE'
})

export const STORE_MODULE_NAME = 'goods'