export const MUTATIONS_KEYS = Object.freeze({
  SET_LIST: 'SET_LIST',
  SET_LOADING: 'SET_LOADING',
  SET_FETCHED: 'SET_FETCHED',
  SET_ITEM: 'SET_ITEM',
  REMOVE_ITEM_FROM_LIST: 'REMOVE_ITEM_FROM_LIST',
  PREPEND_ITEM_TO_LIST: 'PREPEND_ITEM_TO_LIST',
  UPDATE_ITEM_IN_LIST: 'UPDATE_ITEM_IN_LIST',
  SHOW_EDIT_DIALOG: 'SHOW_EDIT_DIALOG',
  SET_EDIT_DIALOG_TYPE: 'SET_EDIT_DIALOG_TYPE',
  SET_EDIT_DIALOG_SOURCE: 'SET_EDIT_DIALOG_SOURCE',
  CLEAN_LIST: 'CLEAN_LIST',
  SET_SUBORDINATE_LIST_COMPANY_GUID: 'SET_SUBORDINATE_LIST_COMPANY_GUID'
})

export const ACTIONS_KEYS = Object.freeze({
  FETCH_LIST: 'FETCH_LIST',
  CREATE_ITEM: 'CREATE_ITEM',
  CHANGE_ITEM: 'CHANGE_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  SHOW_EDIT_DIALOG: 'SHOW_EDIT_DIALOG',
  FETCH_SUBORDINATE_LIST: 'FETCH_SUBORDINATE_LIST'
})

export const STORE_MODULE_NAME = 'organisations'

export const EDIT_DIALOG_TYPES = Object.freeze({
  EDIT: 'editing',
  CREATE: 'creation'
})

export const EDIT_DIALOG_SOURCES = Object.freeze({
  SUBORDINATE: 'subordinate',
  PROFILE: 'profile'
})
